### ISSUE TITLE
Mod Uses FoliageColors Instead of GrassColors.

### ISSUE THREAD

**Issue by theendercore** [Hecco56/Biome-Tinted-Flowers#3]
As title says.
This would be more like vanilla because sort_grass, tall_grass and ferns use it and to would make more sense to use it.
Here is image to explain why (grass color is green, foliage is red):
![image](https://github.com/Hecco56/Biome-Tinted-Flowers/assets/49921297/d414c8f2-9741-432a-b371-7fae0f2523ed)

**Comment by Hecco56** [comment]
I did do this intentionally to differentiate the tint of flowers from grass slightly, but I'll change it in the next update for if mods have differing foliage and grass colors.
